export const Gallery = {
  items: [
    { src: "/assets/gallery/1.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/2.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/3.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/4.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/5.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/6.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/7.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/8.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/9.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/10.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/11.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/12.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/13.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/14.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/15.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/16.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/17.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/18.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/19.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/20.webp", hasPlay: false, alt: "VIT STELLAR" },
    { src: "/assets/gallery/21.webp", hasPlay: false, alt: "VIT STELLAR" },
  ],
};
